// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6vgGkSWixxDwysdU3VGGcw2ge7JYRdk4',
    appId: '1:524188143942:web:36da094fce20d13f1c9547',
    messagingSenderId: '524188143942',
    projectId: 'lich-app',
    authDomain: 'lich-app.firebaseapp.com',
    storageBucket: 'lich-app.firebasestorage.app',
    measurementId: 'G-GTMH3488W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzaHMDcCFL-sStha3T2nx5Aqk2xSFnAbA',
    appId: '1:524188143942:android:40bdf598f28892e61c9547',
    messagingSenderId: '524188143942',
    projectId: 'lich-app',
    storageBucket: 'lich-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVfxgxbdJB2SJheJIbNoHjlECnMIoQLAU',
    appId: '1:524188143942:ios:b6623918b5e27c211c9547',
    messagingSenderId: '524188143942',
    projectId: 'lich-app',
    storageBucket: 'lich-app.firebasestorage.app',
    iosBundleId: 'com.example.lunarSolarCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVfxgxbdJB2SJheJIbNoHjlECnMIoQLAU',
    appId: '1:524188143942:ios:b6623918b5e27c211c9547',
    messagingSenderId: '524188143942',
    projectId: 'lich-app',
    storageBucket: 'lich-app.firebasestorage.app',
    iosBundleId: 'com.example.lunarSolarCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6vgGkSWixxDwysdU3VGGcw2ge7JYRdk4',
    appId: '1:524188143942:web:b5a5ede75d1c34f61c9547',
    messagingSenderId: '524188143942',
    projectId: 'lich-app',
    authDomain: 'lich-app.firebaseapp.com',
    storageBucket: 'lich-app.firebasestorage.app',
    measurementId: 'G-NBWMJLXFK8',
  );
}
